### ISSUE TITLE
Missing PDF output

### ISSUE THREAD

**Issue by spidersouris** [mrtz-j/typst-thesis-template#24]
The README says: "see thesis.pdf for a rendered pdf", but there is nothing in the /template folder, and `*.pdf` is in `.gitignore`. I guess this was done because the Typst package on Typst Universe should not include any PDFs? But this makes it impossible to have a preview of the template or have an easy access to the manual.

I believe the `.gitignore` restriction could be removed from this repo and just be kept in your local typst/packages repo (or, add a whitelist for this repo, e.g. `!template/thesis.pdf`)

**Comment by mrtz-j** [comment]
Yes, we removed it because of the `Typst/Packages` restriction. Right now the `.pdf` is only available as an asset for each `Releases`. I'll discuss it with @otytlandsvik 👍
